apiVersion: v1
kind: Pod
metadata:
  name: APP_NAME
  labels:
    app: APP_NAME
spec:
  containers:
    - name: APP_NAME
      image: tecnobooks.azurecr.io/APP_NAME_GIT
      ports:
        - containerPort: 8080
